
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.13.0  
        with:
         channel: 'stable'
      
      - name: Verify Dependencies
        working-directory: ./app
        run: flutter pub get

      - name: Run Tests
        working-directory: ./app
        run: flutter test

      - name: Build Web Application
        working-directory: ./app
        run: flutter build web

      - name: Web Deploy  - Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:  
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 30d
          projectId: flutteredilemma 
