name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Flutter action
        uses: subosito/flutter-action@v2.13.0

      - name: Verify Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

      - name: Build Web Application
        run: flutter build web

      # You can add more steps here for deployment, notifications, etc.
