name: Build and Test Flutter App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Verify Dependencies
        run: |
          flutter doctor
          flutter pub get || echo "Flutter application dependencies not installed. Run 'flutter pub get' to install them."

      - name: Run Tests
        run: flutter test

      - name: Build Web Application
        run: flutter build web

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: web-build
          path: build/web
