name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.13.0  
        with:
         channel: 'stable'
      
      - name: Verify Dependencies
        working-directory: ./app
        run: flutter pub get

      - name: Run Tests
        working-directory: ./app
        run: flutter test

      - name: Build Web Application
        working-directory: ./app
        run: flutter build web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:  
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/build/web
