name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.13.0
        with:
          channel: 'stable'

      - name: Verify Dependencies
        run: flutter pub get
        working-directory: ./app

      - name: Run Tests
        run: flutter test
        working-directory: ./app

      - name: Build Web Application
        run: flutter build web
        working-directory: ./app

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:  
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./app/build/web/ 
